# Generated by Django 5.1.4 on 2024-12-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('alt', models.TextField()),
                ('transcript', models.TextField()),
                ('img', models.URLField()),
                ('publish_date', models.DateField()),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
