# Generated by Django 5.1.4 on 2024-12-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_rename_alt_comic_alt_text_rename_img_comic_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='embedding_model',
        ),
    ]
